### PR TITLE
Fix AssetText format exception when asset.value exceeding 53 bits

### PR DESCRIPTION
**Pull request by ttwishing**
https://v2.unicove.com/eos/api/account/eosio/balances

{
  contract: 'tttingenesis',
  amount: '288144141.51524401',
  decimals: '8',
  currency: 'TTT'
}
Asset.from(`288144141.51524401 TTT`);

### CODE REVIEW

**Comment by aaroncox** [comment]
Would this would still cause an error if the number exceeded 53 bits?

The quantity value is a string, but it's immediately being cast to a JS number in the same line, which would cause it to throw the error... unless I'm misunderstanding 🤔

**Comment by ttwishing** [comment]
> Would this would still cause an error if the number exceeded 53 bits?
> 
> The quantity value is a string, but it's immediately being cast to a JS number in the same line, which would cause it to throw the error... unless I'm misunderstanding 🤔

Yes, that's my understanding. But no exception when used quantity. I will study it again.

**Comment by ttwishing** [comment]
Number(''1288144141.51524411') will lose precision when the conversion process exceeds the number of significant digits, and the output will be '288,144,141.515244'. My solution is imperfect, I will correct it again

**Comment by aaroncox** [comment]
Here's an alternative pull request using Big.js, which is the library we're using for the input values.

https://github.com/greymass/2nicove/pull/225

**Comment by aaroncox** [comment]
Implemented the other solution for the time being, even if we lose slight precision during math operations. We can address it in future PRs if the inaccuracy becomes a problem.

**Pull request closed without merging**
